version: '3'

services:

  mysql:
    image: mysql:5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    build: ./scripts/docker/wordpress
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wp-content
      - .:/var/www/html/wp-content/plugins/block-scaffolding-wp
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data: {}
  wp_data: {}
